// Copyright 2024 Copyright 2024 The OS Migration Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

edition = "2023";

package os_migration_data_types.v1;

option java_multiple_files = true;

message ExportFailureSummary {
  uint64 untransferable_item_count = 1;
  uint64 failed_item_count = 2;
  repeated string failure_messages = 3;
}

enum ExportFailureState {
  EXPORT_FAILURE_STATE_UNSPECIFIED = 0;
  EXPORT_FAILURE_STATE_UNTRANSFERABLE = 1;
  EXPORT_FAILURE_STATE_EXPORT_FAILED = 2;
}

message ExportFailure {
  ExportFailureState failure_state = 1;
  string failure_message = 2;
}
